---
# handlers file for provision/roles/ospf
- name: "restart quagga"
  service:
    name: "zebra"
    state: "restarted"
    enabled: yes

- name: "restart ospfd"
  service:
    name: "ospfd"
    state: "restarted"
    enabled: yes

