---
# tasks file for provision/roles/icluster-router

- name: add MySQL repo
  yum:
    name: "https://repo.mysql.com/mysql80-community-release-el7-3.noarch.rpm"
    state: present

- name: delete mariadb
  yum:
    name: mariadb-libs
    state: removed

- name: install MySQL Router
  yum:
    name: mysql-router-community
    enablerepo: mysql80-community
    state: present

- name: bootstrap MySQL Router
  shell: echo "Passw0rd" | mysqlrouter --bootstrap icadmin@sqlnode1:3306 --user=mysqlrouter --conf-use-sockets
  args:
    creates: /etc/mysqlrouter/mysqlrouter.conf.bak

- name: start and enable MySQL Router
  systemd:
    name: mysqlrouter
    state: started
    enabled: true

