servers=[
  {
    :hostname => "ipa.otus.lan",
    :ip => "192.168.56.10",
    :box => "centos/7",
    :playbook => "./provision/ipa-server.yml",
    :ram => 2048,
    :cpu => 2
  },
  {
    :hostname => "client.otus.lan",
    :ip => "192.168.56.11",
    :box => "centos/7",
    :playbook => "./provision/ipa-client.yml",
    :ram => 1024,
    :cpu => 2
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provision "ansible" do |ansible|
#                ansible.verbose = "vvv"
                ansible.playbook = machine[:playbook]
            end
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        end
    end
end

