- name: setup nfs server
  hosts: nfsserver
  become: True
  roles:
    - nfs-firewall
    - nfs-server

- name: setup nfs client
  hosts: nfsclient
  become: True
  roles:
    - nfs-firewall
    - nfs-client
