---
- name: install common packages
  yum:
    name: "{{ common_packages }}"
    state: "present"

- name: disable selinux
  selinux:
    state: disabled

- name: install the packages from epel repo
  yum:
    name: "{{ epel_packages }}"
    state: "present"

- name: deploy nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify: "restart nginx"

- name: deploy index html
  template:
    src: "index.html.j2"
    dest: "/usr/share/nginx/html/index.html"
  notify: "restart nginx"

