INTENT_TYPE="internal-net"

MACHINES = {
  :master => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.10', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: INTENT_TYPE},
                     ],
            },
  :slave => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.20', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: INTENT_TYPE},
                     ],
            },
  :backup => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.30', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: INTENT_TYPE},
                     ],
            },
}


hosts_file="127.0.0.1\tlocalhost\n"

MACHINES.each do |hostname,config|  
  config[:net].each do |ip|
    if ip[:virtualbox__intnet]==INTENT_TYPE
      hosts_file=hosts_file+ip[:ip]+"\t"+hostname.to_s+"\n"
    end
  end
end

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        box.vm.provider "virtualbox" do |v|
          v.memory = 1024
        end
        box.vm.provision "shell" do |shell|
          shell.inline = 'echo -e "$1" > /etc/hosts'
          shell.args = [hosts_file]
        end
        box.vm.provision "ansible" do |ansible|
          ansible.verbose = "v"
          ansible.playbook = "provision/playbook.yml"
          ansible.tags = "all"
        end
    end
  end
end

