---
# tasks file for provision/roles/nfs-client

- name: install nfs
  yum:
    name: nfs-utils
    state: present

- name: create mount dir
  file:
    path: /mnt/nfs
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'

- name: mount nfs share
  mount:
    path: /mnt/nfs
    src: nfsserver:/var/nfs
    fstype: nfs
    opts: noauto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14
    state: mounted

- name: create upload dir inside nfs share
  file:
    path: /mnt/nfs/upload
    state: directory
  become_user: vagrant

