servers=[
  {
    :hostname => "repo",
    :ip => "192.168.56.10",
    :box => "centos/7",
    :script => "create_repo.sh",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "client",
    :ip => "192.168.56.11",
    :box => "centos/7",
    :script => "use_repo.sh",
    :ram => 1024,
    :cpu => 2
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provision "shell", path: machine[:script]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        end
    end
end

