# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {adapter: 2, virtualbox__intnet: "router-net"},
                   {adapter: 3, virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, virtualbox__intnet: "router-net"},
                   {adapter: 3, virtualbox__intnet: "router-net"},
                   {adapter: 4, virtualbox__intnet: "testLAN"},
                ]
  },
  
  :testClient1 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, virtualbox__intnet: "testLAN"},
                ]
  },
  :testClient2 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, virtualbox__intnet: "testLAN"},
                ]
  },
  :testServer1 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, virtualbox__intnet: "testLAN"},
                ]
  },
  :testServer2 => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, virtualbox__intnet: "testLAN"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook_bond.yml"
          end            
#            sysctl net.ipv4.conf.all.forwarding=1
#            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
#            ip route add 192.168.0.0/16 via 192.168.255.2
        when "centralRouter"
           box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook_bond.yml"
          end            
#            sysctl net.ipv4.conf.all.forwarding=1
#            ip r del default
#            ip r add default via 192.168.255.1
#            ip r add 192.168.1.0/24 via 192.168.10.1
#            ip r add 192.168.2.0/24 via 192.168.20.1
        when "testClient1"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook.yml"
          end            
        when "testClient2"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook.yml"
          end            
        when "testServer1"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook.yml"
          end            
        when "testServer2"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook.yml"
          end            
        end

      end

  end
end

