MACHINES = {
  :sqlnode1 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.21', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :sqlnode2 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.22', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :sqlnode3 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.23', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :nextcloud => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.10', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :nextcloud2 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.12', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :haproxy1 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.100', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
  :haproxy2 => {
             :box_name => "centos/7",
             :net => [
                      {ip: '192.168.56.200', adapter: 3, netmask: "255.255.255.0"},
                     ],
            },
}


hosts_file="127.0.0.1\tlocalhost\n"

MACHINES.each do |hostname,config|  
  config[:net].each do |ip|
      hosts_file=hosts_file+ip[:ip]+"\t"+hostname.to_s+"\n"
  end
end

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        box.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
        box.vm.provision "shell" do |shell|
          shell.inline = 'echo -e "$1" > /etc/hosts'
          shell.args = [hosts_file]
        end
        box.vm.provision "ansible" do |ansible|
#         ansible.verbose = "v"
          ansible.playbook = "provision/site.yml"
        end
    end
  end
end

