# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.10', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "wan"},
                   {ip: '192.168.1.10', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net1"},
                ]
  },
  :client => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.20', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "wan"},
                   {ip: '192.168.2.10', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net2"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "server"
          box.vm.network "forwarded_port", guest: 1194, host: 1194
        end

      end

  end
end

