---
- name: prepare OS
  hosts: all
  become: yes
  roles:
    - nc-os

- name: setup netdata-master
  hosts: mon
  become: yes
  roles:
    - nc-netdata-master
    - nc-pmm-server

- name: prepare InnoDB Cluster nodes
  hosts:
    - sqlnode1
    - sqlnode2
    - sqlnode3
  become: yes
  roles:
    - icluster-node
    - nc-netdata-slave
    - nc-pmm-client

- name: prepare GlusterFS nodes
  hosts:
    - glnode1
    - glnode2
  become: yes
  roles:
    - nc-gluster-infra
    - nc-gluster-setup
    - nc-netdata-slave

- name: setup GlusterFS
  hosts: glnode2
  become: yes
  roles:
    - nc-gluster-run

- name: setup InnoDB Cluster
  hosts: nextcloud
  become: yes
  roles:
    - icluster-setup

- name: setup MySQL Routers
  hosts: 
    - nextcloud
    - nextcloud2
  become: yes
  roles:
    - icluster-router

- name: setup backend1
  hosts: nextcloud
  become: yes
  roles:
    - nc-gluster-client
    - nc-nginx
    - nc-netdata-slave
    - nc-redis
    - nc-php
    - nc-mysql

- name: install nextcloud app
  hosts: nextcloud
  become: yes
  roles:
    - nc-app
  post_tasks:
    - name: Done!
      debug:
        msg:
          - "Your Nextcloud at https://{{ fqdn }} is ready."
          - "Login with user: {{ nc_admin }} and password: {{ nc_passwd }} "

- name: setup backend2
  hosts: nextcloud2
  become: yes
  roles:
    - nc-gluster-client
    - nc-nginx
    - nc-netdata-slave
    - nc-redis
    - nc-php

- name: setup haproxies
  hosts: 
    - haproxy1
    - haproxy2
  become: yes
  roles:
    - nc-gluster-client
    - nc-ssl
    - nc-haproxy
    - nc-netdata-slave

- name: setup keepalived
  hosts: 
    - haproxy1
    - haproxy2
  become: yes
  roles:
    - nc-keepalived

