# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :R1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.1.0.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1r2-net"},
                   {ip: '10.2.0.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1r3-net"},
                   {ip: '192.168.10.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "u1-net"},
                ]
  },
  
  :R2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.1.0.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r1r2-net"},
                   {ip: '10.3.0.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r2r3-net"},
                   {ip: '192.168.20.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "u2-net"},
                ]
  },
  :R3 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '10.3.0.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "r2r3-net"},
                   {ip: '10.2.0.2', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "r1r3-net"},
                   {ip: '192.168.30.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "u3-net"},
                ]
  },
  
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        case boxname.to_s
        when "R1"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook.yml"
          end
        when "R2"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook.yml"
          end
        when "R3"
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "./provision/playbook.yml"
          end
        end
      end
  end
end
