---
# handlers file for provision/roles/web

- name: "restart nginx"
  systemd:
    name: "nginx"
    state: "restarted"
    enabled: yes

- name: "restart rsyslog"
  systemd:
    name: "rsyslog"
    state: "restarted"

- name: "restart auditd"
  # dont works with service module https://stackoverflow.com/questions/41053331/ansible-how-to-restart-auditd-service-on-centos-7-get-error-about-dependency
  command: service auditd restart

