---
# handlers file for provision/roles/web

- name: "restart nginx"
  systemd:
    name: "nginx"
    state: "restarted"
    enabled: yes

- name: "restart rsyslog"
  systemd:
    name: "rsyslog"
    state: "restarted"

